#!/bin/sh

# This script is used to create a new release of the project.
#
# Requirements: github-cli, jq

print_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -h, --help      Print this help message"
    echo "  --patch         Bump patch version"
    echo "  --minor         Bump minor version"
    echo "  --major         Bump major version"
}

[ "$#" -eq 0 ] && print_help && exit 0

latest_release="$(gh release view --json tagName | jq -r .tagName)"

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            print_help
            exit 0
            ;;
        --patch)
            new_release="$(echo "$latest_release" | awk -F. '{print $1"."$2"."$3+1}')"
            ;;
        --minor)
            new_release="$(echo "$latest_release" | awk -F. '{print $1"."$2+1".0"}')"
            ;;
        --major)
            new_release="$(echo "$latest_release" | awk -F. '{print $1+1".0.0"}')"
            ;;
        *)
            echo "Unknown option: $arg"
            print_help
            exit 1
            ;;
    esac
done

gh create release --generate-notes "$new_release"
exit 0
